# -*- coding: utf-8 -*-
"""w17 github file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RE9SAk11mWXLlk83_EKYjExcHIPmLncC
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, mean_squared_error
from sklearn.preprocessing import StandardScaler

# -------------------------------
# Data Loading and Preprocessing
# -------------------------------

# Load the dataset (Assuming it's a CSV file with clinical and genomic data)
data = pd.read_csv('clinical_genomic_data.csv')

# Extract clinical features and genomic mutations
clinical_data = data[['Age', 'Tumor Size', 'Stage', 'Grade', 'Chemo', 'Hormone', 'Radio', 'PAM50']].values
genomic_data = data.drop(columns=['Survival Time', 'Relapse Status', 'Outcome']).values  # Remove outcome columns

# Standardize the clinical data (Z-score normalization)
scaler = StandardScaler()
clinical_data = scaler.fit_transform(clinical_data)

# Split data into train and test sets
X_train_clinical, X_test_clinical, X_train_genomic, X_test_genomic, y_train, y_test = train_test_split(
    clinical_data, genomic_data, data[['Subtype', 'Relapse', 'Survival']], test_size=0.2, random_state=42
)

# -------------------------------
# FT-Transformer Encoder
# -------------------------------

class FTTransformerEncoder(nn.Module):
    def __init__(self, input_dim_clinical, input_dim_genomic, hidden_dim, num_heads, num_layers, output_dim):
        super(FTTransformerEncoder, self).__init__()

        # Input token embeddings for clinical and genomic features
        self.clinical_embedding = nn.Linear(input_dim_clinical, hidden_dim)
        self.genomic_embedding = nn.Linear(input_dim_genomic, hidden_dim)

        # Transformer layers
        self.encoder_layer = nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=num_heads)
        self.transformer_encoder = nn.TransformerEncoder(self.encoder_layer, num_layers=num_layers)

        # Output layer
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, clinical_input, genomic_input):
        # Embed inputs
        clinical_embedded = self.clinical_embedding(clinical_input)
        genomic_embedded = self.genomic_embedding(genomic_input)

        # Concatenate clinical and genomic token embeddings
        combined_input = torch.cat((clinical_embedded, genomic_embedded), dim=1)

        # Apply Transformer encoder
        transformed_output = self.transformer_encoder(combined_input)

        # Final prediction (multi-task head)
        output = self.output_layer(transformed_output)
        return output

# -------------------------------
# Multi-Task Learning Head (for Survival, Relapse, Subtype)
# -------------------------------

class MultiTaskPredictionHead(nn.Module):
    def __init__(self, hidden_dim):
        super(MultiTaskPredictionHead, self).__init__()

        # Subtype classification head
        self.subtype_head = nn.Linear(hidden_dim, 3)  # Assuming 3 classes

        # Relapse prediction head
        self.relapse_head = nn.Linear(hidden_dim, 1)  # Binary outcome

        # Survival risk estimation head (Cox regression)
        self.survival_head = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        subtype_pred = self.subtype_head(x)
        relapse_pred = self.relapse_head(x)
        survival_pred = self.survival_head(x)
        return subtype_pred, relapse_pred, survival_pred

# -------------------------------
# Full Model with Multi-task Output
# -------------------------------

class FTTransformerModel(nn.Module):
    def __init__(self, input_dim_clinical, input_dim_genomic, hidden_dim, num_heads, num_layers, output_dim):
        super(FTTransformerModel, self).__init__()

        self.encoder = FTTransformerEncoder(input_dim_clinical, input_dim_genomic, hidden_dim, num_heads, num_layers, output_dim)
        self.multi_task_head = MultiTaskPredictionHead(hidden_dim)

    def forward(self, clinical_input, genomic_input):
        # Get the transformer output
        encoder_output = self.encoder(clinical_input, genomic_input)

        # Apply multi-task heads
        subtype_pred, relapse_pred, survival_pred = self.multi_task_head(encoder_output)

        return subtype_pred, relapse_pred, survival_pred

# -------------------------------
# Loss Functions and Training
# -------------------------------

def multi_task_loss(subtype_pred, relapse_pred, survival_pred, y_subtype, y_relapse, y_survival):
    # Cross entropy for subtype classification
    subtype_loss = nn.CrossEntropyLoss()(subtype_pred, y_subtype)

    # Binary cross-entropy for relapse prediction
    relapse_loss = nn.BCEWithLogitsLoss()(relapse_pred, y_relapse.float())

    # Cox proportional hazard loss for survival prediction
    survival_loss = nn.MSELoss()(survival_pred, y_survival)

    # Total loss (combined)
    total_loss = subtype_loss + relapse_loss + survival_loss
    return total_loss

# -------------------------------
# Training Loop
# -------------------------------

optimizer = optim.Adam(model.parameters(), lr=0.001)

# Instantiate model
model = FTTransformerModel(input_dim_clinical=8, input_dim_genomic=20, hidden_dim=128, num_heads=8, num_layers=6, output_dim=128)

# Training loop (example)
epochs = 10
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()

    # Forward pass
    subtype_pred, relapse_pred, survival_pred = model(X_train_clinical, X_train_genomic)

    # Compute loss
    loss = multi_task_loss(subtype_pred, relapse_pred, survival_pred, y_train['Subtype'], y_train['Relapse'], y_train['Survival'])

    # Backpropagation
    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

# -------------------------------
# Evaluation
# -------------------------------

model.eval()
with torch.no_grad():
    subtype_pred, relapse_pred, survival_pred = model(X_test_clinical, X_test_genomic)

    # Evaluate performance for each task
    subtype_acc = accuracy_score(y_test['Subtype'], torch.argmax(subtype_pred, dim=1))
    relapse_auc = roc_auc_score(y_test['Relapse'], torch.sigmoid(relapse_pred).numpy())
    survival_c_index = concordance_index(y_test['Survival'], survival_pred.numpy())

    print(f"Subtype Classification Accuracy: {subtype_acc}")
    print(f"Relapse Prediction AUROC: {relapse_auc}")
    print(f"Survival C-Index: {survival_c_index}")